server {
    listen 80;
    server_name _;
    root /var/www/public; # O segredo do 404 costuma estar aqui

    index index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Conecta no PHP-FPM que o CMD do Dockerfile inicia
        fastcgi_pass 127.0.0.1:9000; 
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Bloqueia acesso a arquivos sensíveis
    location ~ /\.(?!well-known).* {
        deny all;
    }
}